services:
  - type: web
    name: iqtf-enterprise-api
    runtime: node
    buildCommand: npm install && npm run api:build
    startCommand: npm run api:start:prod

    disk:
      name: iqtf-data
      mountPath: /var/data
      sizeGB: 1

    envVars:
      - key: NODE_ENV
        value: production

      - key: DB_PATH
        value: /var/data/iqtf.db
