import { normalizeCmeVision } from "./src/services/cmeVisionNormalizer"

const sample = {
  screenshot_type: "CME Options / Vol2Vol",
  as_of_date: "21,2569",

  underlying_futures: [
    {
      symbol: "GC",
      price: 4626.1,
    },
  ],

  option_series: [
    "OGU6",
    "OG4Q6",
    "OGV6",
    "OGX6",
    "OGZ6",
    "OGF7",
    "OGG7",
    "OGH7",
    "OGJ7",
    "OGM7",
  ],

  option_rows: [
    {
      strike: 4570,
      series: "OGU6",
      call_settle: 94.9,
      put_settle: 19.9,
      call_oi: 103,
      call_oi_change: 4,
      put_oi: 30,
      put_oi_change: 4,
    },
    {
      strike: 4575,
      series: "OGU6",
      call_settle: 91.3,
      put_settle: 21.2,
      call_oi: 275,
      call_oi_change: -282,
      put_oi: 361,
      put_oi_change: 309,
    },
    {
      strike: 4580,
      series: "OGU6",
      call_settle: 87.8,
      put_settle: 22.7,
      call_oi: 81,
      call_oi_change: -3,
      put_oi: 36,
      put_oi_change: 34,
    },
    {
      strike: 4585,
      series: "OGU6",
      call_settle: 84.3,
      put_settle: 24.3,
      call_oi: 50,
      call_oi_change: -2,
      put_oi: 138,
      put_oi_change: 55,
    },
    {
      strike: 4590,
      series: "OGU6",
      call_settle: 81,
      put_settle: 25.9,
      call_oi: 84,
      call_oi_change: 5,
      put_oi: 6,
      put_oi_change: 6,
    },
    {
      strike: 4595,
      series: "OGU6",
      call_settle: 77.7,
      put_settle: 27.6,
      call_oi: 83,
      call_oi_change: -1,
      put_oi: 36,
      put_oi_change: 4,
    },
    {
      strike: 4600,
      series: "OGU6",
      call_settle: 74.5,
      put_settle: 29.4,
      call_oi: 2384,
      call_oi_change: -112,
      put_oi: 425,
      put_oi_change: 294,
    },
    {
      strike: 4605,
      series: "OGU6",
      call_settle: 71.4,
      put_settle: 31.3,
      call_oi: 204,
      call_oi_change: 2,
      put_oi: 80,
      put_oi_change: 20,
    },
    {
      strike: 4610,
      series: "OGU6",
      call_settle: 68.4,
      put_settle: 33.3,
      call_oi: 217,
      call_oi_change: 1,
      put_oi: 26,
      put_oi_change: 16,
    },
    {
      strike: 4615,
      series: "OGU6",
      call_settle: 65.4,
      put_settle: 35.4,
      call_oi: 142,
      call_oi_change: -2,
      put_oi: 15,
      put_oi_change: 1,
    },
    {
      strike: 4620,
      series: "OGU6",
      call_settle: 62.6,
      put_settle: 37.5,
      call_oi: 672,
      call_oi_change: -9,
      put_oi: 457,
      put_oi_change: 15,
    },
    {
      strike: 4625,
      series: "OGU6",
      call_settle: 59.9,
      put_settle: 39.8,
      call_oi: 171,
      call_oi_change: 60,
      put_oi: 140,
      put_oi_change: 32,
    },
    {
      strike: 4630,
      series: "OGU6",
      call_settle: 57.2,
      put_settle: 42.1,
      call_oi: 88,
      call_oi_change: -1,
      put_oi: 37,
      put_oi_change: 4,
    },
    {
      strike: 4635,
      series: "OGU6",
      call_settle: 54.7,
      put_settle: 44.6,
      call_oi: 151,
      call_oi_change: 3,
      put_oi: 20,
      put_oi_change: 19,
    },
    {
      strike: 4640,
      series: "OGU6",
      call_settle: 52.2,
      put_settle: 47.1,
      call_oi: 132,
      call_oi_change: -3,
      put_oi: 6,
      put_oi_change: 0,
    },
  ],

  unreadable_or_missing_information: [],
}

const result = normalizeCmeVision(sample)

console.log("===== CME NORMALIZER OPTION OI TEST =====")
console.dir(result, { depth: null })
